### PR TITLE
Finished program

### PR DESCRIPTION
**Pull request by daherr**
I finished the program, I hope I got it right the first time this time!

### CODE REVIEW

**Comment by daherr** [comment]
I updated the program with a java doc, so you should be able to view it now

**Comment by daherr** [comment]
I'm having some issues with my roll dice button, it doesn't work really, and I'm a bit confused why, it appears to be working and I know I'm using the correct method to update the text. However, I've determined that droll and droll comp aren't updating currently, and after staring at my code for about a half an hour thinking of what to do, I decided that it is probably best to ask for assistance. Thanks!

David

**Comment by daherr** [comment]
Ok fixed the dice, now the gridbag isn't formatting right any thoughts? The commit explains most of it and you can see if you try and run the program

**Comment by daherr** [comment]
Disregard!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I FIGURED IT OUT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I figured it out on my own, AND I used the super complicated gridbag layout too!!! I read a solid two tutorials on how to use it, and now I actually understand how to use gridbaglayout! You'll be receiving the final copy in a few minutes I need to add a few comments here and there and a few other, minor clean ups, but it's done!

**Comment by daherr** [comment]
Ok there ya go! That is my finished game of twenty one! Now if you'l excuse me, my bed is calling my name. Thanks!
David

**Comment by jwoytek** [comment]
That's awesome! Good work! I just got home a little bit ago and then just
sat down to read email now, so I'm sorry I didn't get a chance to see this
and respond earlier. BUT, you did it the right way and made it work. Rock
on!

On Mon, Feb 15, 2016 at 9:24 PM, daherr <notifications@github.com> wrote:

>
> Disregard!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> I FIGURED IT
> OUT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! I figured it
> out on my own, AND I used the super complicated gridbag layout too!!! I
> read a solid two tutorials on how to use it, and now I actually understand
> how to use gridbaglayout! You'll be receiving the final copy in a few
> minutes I need to add a few comments here and there and a few other, minor
> clean ups, but it's done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SJHS-CS0501/GameOfTwentyOne/pull/6#issuecomment-184477949>
> .
>



-- 
Jonathan Woytek
Technology Coordinator
724-226-7883 (w)  |  412-877-9574 (m)
jwoytek@saintjosephhs.com

**Pull request closed without merging**
